version: "2.4"

services:
  app:
    build:
      context: .
      target: dev
    expose:
      - 3000
    volumes:
      - .:/docker-react-nginx
      - ~/Library/Caches/Yarn/docker-react-nginx:/usr/local/share/.cache/yarn/v6
    environment:
      - NODE_ENV=development

  nginx:
    build:
      context: ./nginx
    depends_on:
      - app
    ports:
      - 80:80
